[package]
name = "baiken"
version = "0.10.0"
edition = "2021"
authors = ["yakiimoninja"]
repository = "https://github.com/yakiimoninja/baiken"
description = "A Discord bot that displays Guilty Gear Strive frame data."
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.3.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
dotenv = "0.15"
ureq = { version = "2.4.0", features = ["charset"] }
md-5 = "0.10.5"

# Uncomment for debugging
# tracing = "0.1.29"
# tracing-subscriber = "0.3.3"
